### PR TITLE
feat: add view skills by role

### PR DESCRIPTION
**Pull request by bayberryy**
* feat: add view skills by role

### CODE REVIEW

**Review by regexyl — CHANGES_REQUESTED** [review]
Not sure if it's me but I can't seem to find this feature on the files changed tab >< I guess it should fall under `pages/view-skill.tsx`?

P.s. it's odd that the Telegram bot didn't notify on this PR creation 🤨 (lemme figure it out)

**Comment by bayberryy** [comment]
> Not sure if it's me but I can't seem to find this feature on the files changed tab ><
> 
> I guess it should fall under `pages/view-skill.tsx`?

Its under  `pages/view-skills-by-role.tsx`. Could you see it on your side?

**Comment by regexyl** [comment]
I can't find it [here](https://github.com/is212-team7/is212-g5t7/pull/29/commits/66ce3e9aed921b52f7a551431a5f68fc997b7624) - it seems like only `client/database/roles.ts` is edited.

**Comment by bayberryy** [comment]
> I can't find it [here](https://github.com/is212-team7/is212-g5t7/pull/29/commits/66ce3e9aed921b52f7a551431a5f68fc997b7624) - it seems like only `client/database/roles.ts` is edited.

Maybe I pull request on the wrong branch. I opened a new pull request. 👍

**Pull request closed without merging**
